elasticsearch:
  restart: always
  image: elasticsearch:latest
  volumes:
    - ./elasticsearchdata:/usr/share/elasticsearch/data
logstash:
  restart: always
  image: logstash:latest
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - logstash-conf:/etc/logstash/conf.d
  ports:
    - "5000:5000"
  links:
    - elasticsearch
kibana:
  restart: always
  build: kibana/
  #ports:
    #- "5601:5601"
  links:
    - elasticsearch
nginx:
  restart: always
  image: nginx
  ports: 
    - "8080:8080"
    - "8181:8181"
  links: 
    - kibana
  volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
    - ./nginx/htpasswd:/var/htpasswd
